[package]
name = "bevy-mod-dynamicaudio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.19"
bevy = "0.15"
cpal = "0.15"
fundsp = "0.20"
generic-array = "0.14"
parking_lot = "0.12"
